### ISSUE TITLE
Project Setup

### ISSUE THREAD

**Issue by willyue** [pusateri/DNS-TLS#1]
Hi,

I tried to run your project but this lib is missing.
**libgetdns.6.dylib**

Please help. Thanks

**Comment by pusateri** [comment]
The project is currently just a template to help others understand the complications of initializing the DNS network extension. There is no resolution code in there yet so it won't do anything other than absorb your DNS requests.

It was used for demonstrating the "managed device" requirement for this feature in a radar that I had asked Apple if they could remove.

I just checked in a fix to the project that removes this unused library but it still won't do anything.

See https://dnsdisco.com/iOS-dns-proxy-post.html

**Comment by pusateri** [comment]
Commit reference fa6c0c2b3ab5125aa5ea5c6356531e3592d1c8f2
